server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: ${GRACEFUL_SHUTDOWN_TIMEOUT:15s}
  profiles:
    active: ${ENVIRONMENT:development}
  main:
    banner-mode: off
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: localhost
      database: quoteGarden
      uri: mongodb://mongodb/quoteGarden

environment: ${ENVIRONMENT:development}
